### ISSUE TITLE
Exceptions thrown using web.py

### ISSUE THREAD

**Issue by marr** [marcan/kinlarm#1]
Hi, I'm not sure if this is a python version issue or not, but when I run `python web.py`, I get an exception during a visit to the page: http://localhost:12345

```
2015-04-27 19:53:11,779 INFO: Kinect streamer started
10.0.5.6 - - [27/Apr/2015 19:53:16] "GET / HTTP/1.1" 401 -
10.0.5.6 - - [27/Apr/2015 19:53:18] "GET / HTTP/1.1" 200 -
10.0.5.6 - - [27/Apr/2015 19:53:41] "GET / HTTP/1.1" 200 -
10.0.5.6 - - [27/Apr/2015 19:53:41] "GET /jquery.js HTTP/1.1" 200 -
10.0.5.6 - - [27/Apr/2015 19:53:41] "GET /video HTTP/1.1" 200 -
2015-04-27 19:53:41,201 INFO: Starting video
----------------------------------------
Exception happened during processing of request from ('10.0.5.6', 50507)
Traceback (most recent call last):
  File "/opt/boxen/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/boxen/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/boxen/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/opt/boxen/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/opt/boxen/homebrew/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "web.py", line 113, in do_GET
    self.send_text(self.server.controller.state.__name__.title())
AttributeError: 'NoneType' object has no attribute 'state'
```

**Comment by marcan** [comment]
The main entry point is controller.py, not web.py. Try `python controller.py`.

**Comment by marr** [comment]
aha :) many thanks

Any idea what that's about when sending the email?
Traceback (most recent call last):
  File "./controller.py", line 109, in notify
    mail.send_alert("Motion detected")
  File "/Users/dmarr/src/kinlarm/mail.py", line 22, in send_alert
    smtp.starttls()
  File "/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 644, in starttls
    raise SMTPException("STARTTLS extension not supported by server.")
SMTPException: STARTTLS extension not supported by server.

**Comment by marr** [comment]
Any idea what that's about when sending the email?

```
Traceback (most recent call last):
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 599, in process_request_thread
    self.finish_request(request, client_address)
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 657, in __init__
    self.finish()
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py",
line 716, in finish
    self.wfile.close()
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py",
line 283, in close
    self.flush()
  File
"/opt/boxen/homebrew/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py",
line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by marcan** [comment]
As the message indicates, your mail server does not support TLS, so set SMTP_TLS to False in the config (or get a better mail server :-) ).
